### PR TITLE
This fixes the problem with KVM problem.  When you switch keyboads

### PR DESCRIPTION
**Pull request by rac8006**
autopoweroff the threads that monitor keyboard and mouse activity
terminate.  When the keyboard or mouse is removed from the PC.
When the keyboard and mouse is switched back the /dev/input/mouse1 file is created.
So instead of terminating the thread we close the file wait for the /dev/input/mouse1
file which indicates the device have returned.  So reopen the file and go back to monitoring
for activity.

### CODE REVIEW

**Comment by deragon** [comment]
Greetings.  In Autopoweroff 4.0.0, I have, I believe, fixed this.  Please confirm in the related issue.  The code in this pull request is not compatible anymore with the base code.  But thanks for working with me!  I really appreciated it.

**Comment by rac8006** [comment]
I will try to test you code tomorrow.  I think I can just cd / tar -zxf autopoweroff-4.0.0.0.gz file to install your code.

I tried to install your source and build a .deb file.  But had trouble.  No matter what I did I could not get it to create the packages/deb stuff.

Here is the code that I used to setup systemd.

command to start systemctl start autopoweroff
command to stop systemctl stop autopoweroff

new directory /etc/systemy/system/multi-user.target.wants
Filename = autopoweroff.service  located in the new directory
With the following contents.

[Unit]
Description=autopoweroff daemon
After=network.target

[Service]
Type=simple
User=root
NotifyAccess=all
PIDFile=/var/run/autopoweroffd/autopoweroffd.pid
ExecStart=/usr/sbin/autopoweroffd start
RemainAfterExit=true
ExecStop=/usr/sbin/autopoweroffd stop
ExecReload=/usr/sbin/autopoweroffd reload

[Install]
WantedBy=multi-user.target

Sent from Mail for Windows 10

**Comment by deragon** [comment]
You do not have to build yourself the binaries.  *.deb and *.rpm are available for each release.  The latest one can be found at:  [Release 4.0.0](https://github.com/deragon/autopoweroff/releases/tag/4.0.0).

I quickly tried your recipe for systemd but it did not work.  Obviously, something is missing.  One day, I will work on systemd.  Thank you!

**Comment by rac8006** [comment]
Not sure if this is the problem.  But the autopoweroff.service file is also in /etc/system/system directory.  
Yes I don’t need to build the to test.  But I do need to build if I want to fold my disk activity stuff


Sent from Mail for Windows 10

**Pull request closed without merging**
